### ISSUE TITLE
how to fix speed of game

### ISSUE THREAD

**Issue by vietnux** [rugovit/-Green-Valley-Defense#1]
Hello 
I like your game, but:
**how** to fix speed of game?
It has animation very slow :|

**Comment by rugovit** [comment]
Thank you!
You can increase speed of  individual elements.  Every GameObject measures absolute time  and calculate its speed based on that.  
You can setup global variables in FazeIgre.java 
```java	
        public float koeficijentBrzine=1.6f; // defenders speed  factor
	public float koeficijentBrzineProtivnika=2f; //zombies speed factor
```

I will comment some of the factors in English  and make a new commit. 

Sprite animation speed is set while adding  sprite image : 

```java
SpriteHendler.dodajNoviSprite(Bitmap b, int brS, int brR, float brPriPoSec)
```

where ```float brPriPoSec ``` basically represents frame rate

**Comment by vietnux** [comment]
thank you very much!
:D

**Comment by vietnux** [comment]
GUI of game
can you to shared?
tks you

**Comment by rugovit** [comment]
What do you mean?

**Comment by vietnux** [comment]
I would like to ask you for the original GUI you designed for the game. With file is AI or PSD or ... other extends.
please
tks you

**Comment by rugovit** [comment]
Oh I see. Sorry , I wish I was smart enough to save it on a cloud.  It got lost :/. 
What are you trying to do if you don't mind me asking :D

**Comment by vietnux** [comment]
> 
> 
> Oh I see. Sorry , I wish I was smart enough to save it on a cloud. It got lost :/.
> What are you trying to do if you don't mind me asking :D

I am trying to control your game to game speed changer and some graphics.
If you do not mind

**Comment by rugovit** [comment]
It is open source you can use it how ever you want :D.  
Good luck!
